-- VHDL Entity my_project_lib.fsm.symbol
--
-- Created:
--          by - Owner.UNKNOWN (DESKTOP-BED4071)
--          at - 11:34:49 12/31/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2007.1 (Build 19)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY fsm IS
   PORT( 
      clk : IN     std_logic;
      rst : IN     std_logic;
      x   : IN     std_logic;
      y   : OUT    std_logic
   );

-- Declarations

END fsm ;

--
-- VHDL Architecture my_project_lib.fsm.fsm
--
-- Created:
--          by - Owner.UNKNOWN (DESKTOP-BED4071)
--          at - 11:34:49 12/31/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2007.1 (Build 19)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
 
ARCHITECTURE fsm OF fsm IS

   TYPE STATE_TYPE IS (
      s0,
      s1,
      s2,
      s3
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

   -- Declare any pre-registered internal signals
   SIGNAL y_cld : std_logic ;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      clk,
      rst
   )
   -----------------------------------------------------------------
   BEGIN
      IF (rst = '0') THEN
         current_state <= s0;
      ELSIF (clk'EVENT AND clk = '1') THEN
         current_state <= next_state;

         -- Combined Actions
         CASE current_state IS
            WHEN s0 => 
               IF (x='1') THEN 
                  y_cld<='0';
               ELSIF (x='0') THEN 
                  y_cld<='0';
               END IF;
            WHEN s1 => 
               IF (x='0') THEN 
                  y_cld<='0';
               ELSIF (x='1') THEN 
                  y_cld<='0';
               END IF;
            WHEN s2 => 
               IF (x='1') THEN 
                  y_cld<='0';
               ELSIF (x='0') THEN 
                  y_cld<='0';
               END IF;
            WHEN s3 => 
               IF (x='1') THEN 
                  y_cld<='1';
               ELSIF (x='0') THEN 
                  y_cld<='0';
               END IF;
            WHEN OTHERS =>
               NULL;
         END CASE;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      current_state,
      x
   )
   -----------------------------------------------------------------
   BEGIN
      CASE current_state IS
         WHEN s0 => 
            IF (x='1') THEN 
               next_state <= s1;
            ELSIF (x='0') THEN 
               next_state <= s0;
            ELSE
               next_state <= s0;
            END IF;
         WHEN s1 => 
            IF (x='0') THEN 
               next_state <= s2;
            ELSIF (x='1') THEN 
               next_state <= s1;
            ELSE
               next_state <= s1;
            END IF;
         WHEN s2 => 
            IF (x='1') THEN 
               next_state <= s3;
            ELSIF (x='0') THEN 
               next_state <= s0;
            ELSE
               next_state <= s2;
            END IF;
         WHEN s3 => 
            IF (x='1') THEN 
               next_state <= s1;
            ELSIF (x='0') THEN 
               next_state <= s2;
            ELSE
               next_state <= s3;
            END IF;
         WHEN OTHERS =>
            next_state <= s0;
      END CASE;
   END PROCESS nextstate_proc;
 
   -- Concurrent Statements
   -- Clocked output assignments
   y <= y_cld;
END fsm;
