-- VHDL Entity my_project_lib.rts.symbol
--
-- Created:
--          by - Owner.UNKNOWN (DESKTOP-BED4071)
--          at - 20:55:32 12/ 2/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2007.1 (Build 19)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY rts IS
   PORT( 
      a  : IN     std_logic_vector (2 DOWNTO 0);
      y2 : OUT    std_logic
   );

-- Declarations

END rts ;

--
-- VHDL Architecture my_project_lib.rts.struct
--
-- Created:
--          by - Owner.UNKNOWN (DESKTOP-BED4071)
--          at - 20:55:32 12/ 2/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2007.1 (Build 19)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY my_project_lib;

ARCHITECTURE struct OF rts IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL y  : std_logic_vector(7 DOWNTO 0);
   SIGNAL y1 : std_logic_vector(2 DOWNTO 0);


   -- Component Declarations
   COMPONENT comparator
   PORT (
      a : IN     std_logic_vector (2 DOWNTO 0);
      b : IN     std_logic_vector (2 DOWNTO 0);
      y : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT decoder
   PORT (
      a : IN     std_logic_vector (2 DOWNTO 0);
      y : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT encoder
   PORT (
      a : IN     std_logic_vector (7 DOWNTO 0);
      y : OUT    std_logic_vector (2 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : comparator USE ENTITY my_project_lib.comparator;
   FOR ALL : decoder USE ENTITY my_project_lib.decoder;
   FOR ALL : encoder USE ENTITY my_project_lib.encoder;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_2 : comparator
      PORT MAP (
         a => y1,
         b => a,
         y => y2
      );
   U_0 : decoder
      PORT MAP (
         y => y,
         a => a
      );
   U_1 : encoder
      PORT MAP (
         a => y,
         y => y1
      );

END struct;
